# Generated by Django 4.2.5 on 2023-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZCApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='Tipo_limpieza',
        ),
        migrations.AddField(
            model_name='servicios',
            name='Tipo_limpieza',
            field=models.CharField(choices=[('LIMPIEZA PROFUNDA', 'limpieza profunda'), ('LIMPIEZA NORMAL', 'limpieza normal'), ('LIMPIEZA LIGERA', 'limpieza ligera')], default='limpieza ligera', max_length=255, verbose_name='Tipo de limpieza'),
        ),
    ]
