# Generated by Django 4.2.5 on 2023-12-22 03:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ZCApp', '0002_remove_categoria_tipo_limpieza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_servicios',
            name='Direccion_limpieza',
            field=models.CharField(max_length=255, verbose_name='Lugar para realizar el servicio'),
        ),
        migrations.AlterField(
            model_name='solicitud_servicios',
            name='Fecha_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='solicitud_servicios',
            name='telefono_contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Número telefónico'),
        ),
    ]
