# Generated by Django 4.2.5 on 2023-12-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZCApp', '0005_alter_servicios_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_servicios',
            name='Direccion_limpieza',
            field=models.CharField(max_length=255, verbose_name='Dirección del lugar'),
        ),
    ]
